name: products
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  csv: ^5.1.0
  dart_phonetics: ^1.0.1
  file_picker: ^6.0.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.0.4
  path: ^1.8.3
  provider: ^6.0.5
  standard_dialogs: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Splash.png
   